Feature/101 support timeout seconds in the task states
aclavio/marklogic-state-conductor pull request #113
Opened 2020-07-09 20:37 UTC by freshie

2020-09-14 17:56 UTC, aclavio commented
@freshie Can you add unit tests to this PR and resubmit?

2020-09-30 17:23 UTC, freshie commented
> @freshie Can you add unit tests to this PR and resubmit?

I've added a unit test to this to the driver unit tests

2020-09-30 20:27 UTC, aclavio requested changes
Everything looks good minus the typo.

2020-09-30 20:27 UTC, aclavio commented on state-conductor-example/src/test/java/com/marklogic/DriverServiceTest.java
> +    atch.add("/test/stateConductorJob/jobTimeOut.json", jobMeta, loadTokenizedResource("jobs/jobTimeOut.json", tokens));
looks like a typo here.  Missing `b`.

2020-10-01 14:40 UTC, freshie commented on state-conductor-example/src/test/java/com/marklogic/DriverServiceTest.java
> +    atch.add("/test/stateConductorJob/jobTimeOut.json", jobMeta, loadTokenizedResource("jobs/jobTimeOut.json", tokens));
must have had my courser there and delete the b after testing it because it worked before for me. I've fixed it now.

2020-10-01 14:40 UTC, merged