Issue #92 - Refactor Flow and Job to StateMachine and Execution
aclavio/marklogic-state-conductor pull request #128
Opened 2020-09-18 23:38 UTC by mtcotton

2020-09-18 23:39 UTC, mtcotton commented
Saving as draft until I can test with a clean project, but junit and mlunittests pass

2020-09-25 14:16 UTC, aclavio requested changes

2020-09-25 14:16 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/custom-steps-state-machine.asl.json
> +        "name": "CustomFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:16 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/missing-dhf-state-machine.asl.json
> +        "name": "MissingFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:16 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:16 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-steps-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:16 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-steps-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:18 UTC, merged