Issue #92 - Refactor Flow and Job to StateMachine and Execution (#128)
aclavio/marklogic-state-conductor pull request #129
Opened 2020-09-25 14:20 UTC by aclavio

Fixes #92

2020-09-25 14:22 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/custom-steps-state-machine.asl.json
> +        "name": "CustomFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:22 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/missing-dhf-state-machine.asl.json
> +        "name": "MissingFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:22 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:22 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-steps-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-09-25 14:22 UTC, aclavio commented on state-conductor-dhf5-example/src/test/ml-modules/root/test/suites/StateConductorDHF5Suite/test-data/stateMachines/person-steps-state-machine.asl.json
> +        "name": "PersonFlow",
rollback to keep DHF naming convention of "flowName"

2020-10-02 16:40 UTC, freshie requested changes
added .DS_Store to git ignore

2020-10-02 16:40 UTC, freshie commented on state-conductor-modules/src/main/ml-config/databases/state-conductor-jobs-database.json
> +  "database-name": "state-conductor-executions",
the Name of this file should be changed as well

2020-10-02 16:40 UTC, freshie commented on state-conductor-modules/src/main/ml-modules/root/state-conductor/state-conductor.sjs
> +        fn.error(null, 'MISSING-STATE_MACHINE-FILE', `Cannot find a a stateMachine file with the name: ${name}`);
I think there is a type O from before with two "a" next to each other

2020-10-02 20:02 UTC, freshie commented on state-conductor-cpf/src/main/ml-modules/root/state-conductor/cpf/state-conductor-work-action.sjs
> +    const continueExecution = sc.processExecution(uri);
Will have another commit to remove cpf stuff.

2020-10-06 19:46 UTC, freshie approved these changes

2020-10-15 17:05 UTC, closed without merging

2020-10-15 17:06 UTC, freshie commented
i'm going to push changes from my own branch as this one isn't updating.